### PR TITLE
Update WelcomeFragment, add Privacy page, UI changes

### PR DESCRIPTION
**Pull request by kking**

### CODE REVIEW

**Comment by IHFSchwarz** [comment]
Hey!

Thank you for your pull request.
I haven't been active on this repo since I'm no longer employed but purely studying.
Its probably not quite up to my code standards nowadays so thank you for working with it.
I have exams soon but also still have some love for the DAPNET so I'll check it out during the week.

**Comment by kking** [comment]
Thank you in advance for taking your time to review my pull request. I hope that these changes provide a meaningful contribution to the user experience. This was a great lesson for me in open-source development, so any questions/comments/feedback are greatly appreciated!

**Comment by dh3wr** [comment]
Hi @kking
I finally managed to review your code. Awesome updatesm thanks for that. I personally am no tne expert on android programming, so I was very happy @IHFSchwarz was doing an excelent job in the past.
I've running your code in the Android Studio emulator and just have one request:
The map button is always visible, although the screen is not displaying any map-related content. This could confuse users. Would it be able to change the visibility of that map button depending if there is any map on the screen?

I will accept your change request in the mean time an learn how to publish updates on google play.

BR and hapyy christmas
Ralf

**Comment by dh3wr** [comment]
Update is uploaded as version 1.2.0 and waiting for approval.

**Pull request merged**
